apiVersion: v1
kind: Pod
metadata:
  labels:
    cloud-config: k8s-dev
spec:
  containers:
  - name: dind
    image: 'docker:18-dind'
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
    resources:
      limits:
        cpu: 6000m
        memory: 16Gi
      requests:
        cpu: 2000m
        memory: 4Gi
  volumes:
    - name: dind-storage
      emptyDir: {}
  imagePullSecrets:
    - name: nexusdockersecret
